import {
  LoaderCircle,
  Snowflake,
  Sun,
  Leaf,
  Sprout,
  GraduationCap,
  Book,
  FlaskConical,
  Presentation,
  Users,
} from "lucide-react";

export const icons = {
  LoaderCircle,
  Snowflake,
  Sun,
  Leaf,
  Sprout,
  GraduationCap,
};

export const seasonColors = {
  winter: "text-blue-500",
  spring: "text-green-500",
  summer: "text-yellow-500",
  fall: "text-orange-500",
  default: "text-gray-500",
};

export const seasonIcons = {
  winter: Snowflake,
  spring: Sprout,
  summer: Sun,
  fall: Leaf,
  default: GraduationCap,
};

export const classTypeIcons = {
  lecture: Presentation,
  tutorial: Book,
  lab: FlaskConical,
  seminar: Users,
  default: Book,
};

export const colors: Color[] = [
  "red",
  "orange",
  "yellow",
  "green",
  "cyan",
  "blue",
  "purple",
  "pink",
];

export const eventColors = {
  red: "bg-red-500 border-red-300 dark:bg-red-700 dark:border-red-900 text-white hover:bg-red-500 hover:dark:bg-red-700",
  orange:
    "bg-orange-500 border-orange-300 dark:bg-orange-700 dark:border-orange-900 text-white hover:bg-orange-500 hover:dark:bg-orange-700",
  yellow:
    "bg-yellow-400 border-yellow-300 dark:bg-yellow-500 dark:border-yellow-700 text-white hover:bg-yellow-400 hover:dark:bg-yellow-500",
  green:
    "bg-green-500 border-green-300 dark:bg-green-700 dark:border-green-900 text-white hover:bg-green-500 hover:dark:bg-green-700",
  cyan: "bg-cyan-500 border-cyan-300 dark:bg-cyan-700 dark:border-cyan-900 text-white hover:bg-cyan-500 hover:dark:bg-cyan-700",
  blue: "bg-blue-500 border-blue-300 dark:bg-blue-700 dark:border-blue-900 text-white hover:bg-blue-500 hover:dark:bg-blue-700",
  purple:
    "bg-purple-500 border-purple-300 dark:bg-purple-700 dark:border-purple-900 text-white hover:bg-purple-500 hover:dark:bg-purple-700",
  pink: "bg-pink-500 border-pink-300 dark:bg-pink-700 dark:border-pink-900 text-white hover:bg-pink-500 hover:dark:bg-pink-700",
  fallback:
    "bg-zinc-500 border-zinc-300 dark:bg-zinc-700 dark:border-zinc-900 text-white hover:bg-zinc-500 hover:dark:bg-zinc-700",
};

export const lightEventColors = {
  red: "bg-red-500 border-red-300 text-white hover:bg-red-500",
  orange: "bg-orange-500 border-orange-300 text-white hover:bg-orange-500",
  yellow: "bg-yellow-400 border-yellow-300 text-white hover:bg-yellow-400",
  green: "bg-green-500 border-green-300 text-white hover:bg-green-500",
  cyan: "bg-cyan-500 border-cyan-300 text-white hover:bg-cyan-500",
  blue: "bg-blue-500 border-blue-300 text-white hover:bg-blue-500",
  purple: "bg-purple-500 border-purple-300 text-white hover:bg-purple-500",
  pink: "bg-pink-500 border-pink-300 text-white hover:bg-pink-500",
  fallback: "bg-zinc-500 border-zinc-300 text-white hover:bg-zinc-500",
};

export const weekdays = [
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
];

export const backgroundOptions: {
  value: BackgroundType;
  label: string;
  preview: string;
  light: string;
  dark: string;
}[] = [
  {
    value: "plain",
    label: "Plain",
    preview: "bg-gradient-to-b from-white to-zinc-300",
    light: "bg-gradient-to-b from-white to-zinc-100",
    dark: "bg-gradient-to-b from-zinc-800 to-zinc-950",
  },
  {
    value: "ice",
    label: "Ice",
    preview: "bg-gradient-to-b from-sky-300 to-blue-500",
    light: "bg-gradient-to-b from-sky-100 to-blue-200",
    dark: "bg-gradient-to-b from-sky-500 to-blue-800",
  },
  {
    value: "fire",
    label: "Fire",
    preview: "bg-gradient-to-b from-orange-400 to-red-500",
    light: "bg-gradient-to-b from-orange-100 to-red-200",
    dark: "bg-gradient-to-b from-orange-500 to-red-800",
  },
  {
    value: "sunset",
    label: "Sunset",
    preview: "bg-gradient-to-b from-amber-300 via-orange-400 to-rose-500",
    light: "bg-gradient-to-b from-amber-100 via-orange-200 to-rose-300",
    dark: "bg-gradient-to-b from-orange-500 via-rose-600 to-purple-800",
  },
  {
    value: "aurora",
    label: "Aurora",
    preview: "bg-gradient-to-b from-emerald-400 via-teal-400 to-violet-500",
    light: "bg-gradient-to-b from-emerald-100 via-teal-200 to-violet-200",
    dark: "bg-gradient-to-b from-emerald-600 via-cyan-700 to-violet-800",
  },
  {
    value: "ocean",
    label: "Ocean",
    preview: "bg-gradient-to-b from-cyan-400 via-sky-500 to-blue-600",
    light: "bg-gradient-to-b from-cyan-100 via-sky-200 to-blue-300",
    dark: "bg-gradient-to-b from-teal-600 via-cyan-700 to-indigo-900",
  },
  {
    value: "forest",
    label: "Forest",
    preview: "bg-gradient-to-b from-lime-400 via-green-500 to-emerald-600",
    light: "bg-gradient-to-b from-lime-100 via-green-200 to-emerald-300",
    dark: "bg-gradient-to-b from-green-600 via-green-700 to-emerald-900",
  },
  {
    value: "lavender",
    label: "Lavender",
    preview: "bg-gradient-to-b from-violet-400 via-purple-500 to-fuchsia-500",
    light: "bg-gradient-to-b from-violet-100 via-purple-200 to-fuchsia-200",
    dark: "bg-gradient-to-b from-violet-600 via-purple-700 to-fuchsia-900",
  },
  {
    value: "mint",
    label: "Mint",
    preview: "bg-gradient-to-b from-teal-300 via-cyan-400 to-emerald-500",
    light: "bg-gradient-to-b from-teal-100 via-cyan-100 to-emerald-200",
    dark: "bg-gradient-to-b from-teal-600 via-cyan-700 to-emerald-800",
  },
  {
    value: "galaxy",
    label: "Galaxy",
    preview: "bg-gradient-to-b from-indigo-400 via-purple-500 to-pink-500",
    light: "bg-gradient-to-b from-indigo-200 via-purple-200 to-pink-200",
    dark: "bg-gradient-to-b from-slate-900 via-purple-900 to-violet-800",
  },
  {
    value: "rose",
    label: "Rose",
    preview: "bg-gradient-to-b from-pink-400 via-rose-500 to-red-500",
    light: "bg-gradient-to-b from-pink-100 via-rose-200 to-red-200",
    dark: "bg-gradient-to-b from-pink-600 via-rose-700 to-red-900",
  },
  {
    value: "midnight",
    label: "Midnight",
    preview: "bg-gradient-to-b from-slate-500 via-blue-800 to-indigo-900",
    light: "bg-gradient-to-b from-slate-200 via-blue-200 to-indigo-300",
    dark: "bg-gradient-to-b from-slate-900 via-blue-950 to-indigo-950",
  },
];

// Mock display events used on the marketing/landing page. These follow the
// `LocalEvent` shape (snake_case, no joined course object) so they render
// the same way as guest-mode IndexedDB events.
export const displayEvents1: LocalEvent[] = [
  {
    course_code: "ENDG 319",
    course: null,
    type: "lecture",
    days: ["monday", "wednesday", "friday"],
    start_time: "08:00",
    end_time: "08:50",
    location: "Engineering Block C 70",
    course_color: "blue",
    term: null,
    recurrence: "weekly",
  },
  {
    course_code: "ENDG 319",
    course: null,
    type: "tutorial",
    days: ["tuesday"],
    start_time: "08:00",
    end_time: "09:15",
    location: "Science Theatres 143",
    course_color: "blue",
    term: null,
    recurrence: "weekly",
  },
  {
    course_code: "ECON 201",
    course: null,
    type: "tutorial",
    days: ["thursday"],
    start_time: "08:30",
    end_time: "09:20",
    location: "Social Science 113",
    course_color: "red",
    term: null,
    recurrence: "weekly",
  },
  {
    course_code: "ENEL 353",
    course: null,
    type: "lecture",
    days: ["monday", "wednesday", "friday"],
    start_time: "09:00",
    end_time: "09:50",
    location: "Science Theatres 141",
    course_color: "yellow",
    term: null,
    recurrence: "weekly",
  },
  {
    course_code: "ECON 201",
    course: null,
    type: "lecture",
    days: ["tuesday", "thursday"],
    start_time: "09:30",
    end_time: "10:45",
    location: "Murray Fraser Hall 162",
    course_color: "red",
    term: null,
    recurrence: "weekly",
  },
  {
    course_code: "ENSF 337",
    course: null,
    type: "lecture",
    days: ["monday", "wednesday", "friday"],
    start_time: "11:00",
    end_time: "11:50",
    location: "Info & Communication Tech 122",
    course_color: "orange",
    term: null,
    recurrence: "weekly",
  },
  {
    course_code: "ENEL 353",
    course: null,
    type: "tutorial",
    days: ["monday"],
    start_time: "12:00",
    end_time: "12:50",
    location: "Science Theatres 145",
    course_color: "yellow",
    term: null,
    recurrence: "weekly",
  },
  {
    course_code: "ENSF 300",
    course: null,
    type: "lecture",
    days: ["tuesday", "thursday"],
    start_time: "12:30",
    end_time: "13:45",
    location: "Info & Communication Tech 319",
    course_color: "green",
    term: null,
    recurrence: "weekly",
  },
  {
    course_code: "ENSF 300",
    course: null,
    type: "lab",
    days: ["monday"],
    start_time: "15:00",
    end_time: "16:50",
    location: "Info & Communication Tech 319",
    course_color: "green",
    term: null,
    recurrence: "weekly",
  },
  {
    course_code: "ENEL 353",
    course: null,
    type: "lab",
    days: ["tuesday"],
    start_time: "15:30",
    end_time: "18:15",
    location: "Engineering Block G 130",
    course_color: "yellow",
    term: null,
    recurrence: "weekly",
  },
  {
    course_code: "ENSF 337",
    course: null,
    type: "lab",
    days: ["friday"],
    start_time: "15:00",
    end_time: "16:50",
    location: "Off-Site Web-Based",
    course_color: "orange",
    term: null,
    recurrence: "weekly",
  },
];

export const displayEvents2: LocalEvent[] = [
  {
    course_code: "PHYS 259",
    course: null,
    type: "lecture",
    days: ["wednesday"],
    start_time: "08:00",
    end_time: "10:45",
    location: "Engineering Block G 24",
    course_color: "cyan",
    term: null,
    recurrence: "weekly",
  },
  {
    course_code: "ENGG 212",
    course: null,
    type: "lecture",
    days: ["thursday"],
    start_time: "08:00",
    end_time: "10:45",
    location: "Info & Communication Tech 114",
    course_color: "red",
    term: null,
    recurrence: "weekly",
  },
  {
    course_code: "ENGG 200",
    course: null,
    type: "lecture",
    days: ["friday"],
    start_time: "08:00",
    end_time: "10:45",
    location: "Info & Communication Tech 217",
    course_color: "blue",
    term: null,
    recurrence: "weekly",
  },
  {
    course_code: "ENGG 200",
    course: null,
    type: "lab",
    days: ["monday", "tuesday"],
    start_time: "09:00",
    end_time: "09:50",
    location: "Info & Communication Tech 217",
    course_color: "blue",
    term: null,
    recurrence: "weekly",
  },
  {
    course_code: "MATH 277",
    course: null,
    type: "lab",
    days: ["monday"],
    start_time: "10:00",
    end_time: "10:50",
    location: "Info & Communication Tech 114",
    course_color: "pink",
    term: null,
    recurrence: "weekly",
  },
  {
    course_code: "PHYS 259",
    course: null,
    type: "lab",
    days: ["tuesday"],
    start_time: "10:00",
    end_time: "10:50",
    location: "Engineering Block G 03",
    course_color: "cyan",
    term: null,
    recurrence: "weekly",
  },
  {
    course_code: "ENGG 202",
    course: null,
    type: "lecture",
    days: ["wednesday"],
    start_time: "11:00",
    end_time: "12:50",
    location: "Info & Communication Tech 217",
    course_color: "purple",
    term: null,
    recurrence: "weekly",
  },
  {
    course_code: "MATH 277",
    course: null,
    type: "lecture",
    days: ["friday"],
    start_time: "11:00",
    end_time: "12:50",
    location: "Engineering Block G 24",
    course_color: "pink",
    term: null,
    recurrence: "weekly",
  },
  {
    course_code: "ENGG 202",
    course: null,
    type: "tutorial",
    days: ["monday", "tuesday"],
    start_time: "12:00",
    end_time: "12:45",
    location: "Engineering Block E 123",
    course_color: "purple",
    term: null,
    recurrence: "weekly",
  },
  {
    course_code: "ENGG 200",
    course: null,
    type: "seminar",
    days: ["tuesday"],
    start_time: "14:00",
    end_time: "14:50",
    location: "Engineering Block G 24",
    course_color: "blue",
    term: null,
    recurrence: "weekly",
  },
  {
    course_code: "ENGG 212",
    course: null,
    type: "lab",
    days: ["monday", "tuesday"],
    start_time: "15:00",
    end_time: "15:45",
    location: "Engineering Block G 224",
    course_color: "red",
    term: null,
    recurrence: "weekly",
  },
];
