import { defineConfig, globalIgnores } from "eslint/config";
import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypeScript from "eslint-config-next/typescript";

export default defineConfig([
  globalIgnores([
    ".next/**",
    "next-env.d.ts",
    // Generated by `npm run types:gen` — regenerating would undo any edits.
    "types/supabase.ts",
    // Scratch state written by `supabase start`, including edge-runtime
    // bootstrap code that is not ours to lint.
    "supabase/.temp/**",
  ]),
  nextCoreWebVitals,
  nextTypeScript,
  {
    rules: {
      // Allow intentionally unused args/vars when prefixed with an underscore.
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrors: "all",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
    },
  },
  {
    // The form-field wrappers accept `UseFormReturn<any>` on purpose: they are
    // generic over every form shape in the app, and threading a type parameter
    // through each one buys no real safety at the call sites.
    files: ["components/form-fields/**/*.tsx", "**/*.d.ts"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
    },
  },
]);
