-- Email notifications for incoming friend requests.
--
-- Two pieces: a per-user opt-out on `users`, and a ledger of what has already
-- been sent. The ledger is what makes a duplicate impossible — the row is
-- claimed through the unique index below *before* the message is handed to
-- Resend, so a double submit, a retry, or a second server instance finds the
-- key taken and sends nothing.

alter table "public"."users"
  add column "email_friend_requests" boolean not null default true;


  create table "public"."email_notifications" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "recipient" uuid not null,
    "type" text not null,
    "friendship_id" bigint,
    "provider_id" text
      );


alter table "public"."email_notifications" enable row level security;

CREATE UNIQUE INDEX email_notifications_pkey ON public.email_notifications USING btree (id);

-- The dedupe key: one message per recipient, per kind, per subject.
CREATE UNIQUE INDEX email_notifications_dedupe_key ON public.email_notifications USING btree (recipient, type, friendship_id);

CREATE INDEX email_notifications_recipient_idx ON public.email_notifications USING btree (recipient, created_at DESC);

alter table "public"."email_notifications" add constraint "email_notifications_pkey" PRIMARY KEY using index "email_notifications_pkey";

alter table "public"."email_notifications" add constraint "email_notifications_recipient_fkey" FOREIGN KEY (recipient) REFERENCES public.users(id) ON DELETE CASCADE not valid;

alter table "public"."email_notifications" validate constraint "email_notifications_recipient_fkey";

-- Declining a request deletes the friendship row, which takes its ledger entry
-- with it and leaves the same person free to be notified if they ask again
-- later. What stops a cancel-and-resend loop from becoming a stream of mail is
-- the per-recipient throttle in the application, not this table.
alter table "public"."email_notifications" add constraint "email_notifications_friendship_fkey" FOREIGN KEY (friendship_id) REFERENCES public.friendships(id) ON DELETE CASCADE not valid;

alter table "public"."email_notifications" validate constraint "email_notifications_friendship_fkey";

-- Nothing outside the server ever reads this table. It records who was mailed
-- and when, which is not the requester's business and not the recipient's
-- either, so no policy is written for `authenticated` and the grants are
-- withdrawn to match. Sending runs under the service role, which bypasses RLS.
revoke all on table "public"."email_notifications" from "anon";

revoke all on table "public"."email_notifications" from "authenticated";

grant delete on table "public"."email_notifications" to "service_role";

grant insert on table "public"."email_notifications" to "service_role";

grant references on table "public"."email_notifications" to "service_role";

grant select on table "public"."email_notifications" to "service_role";

grant trigger on table "public"."email_notifications" to "service_role";

grant truncate on table "public"."email_notifications" to "service_role";

grant update on table "public"."email_notifications" to "service_role";
