create type "public"."friendship_status" as enum ('pending', 'accepted');


  create table "public"."friendships" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "requester" uuid not null,
    "addressee" uuid not null,
    "status" public.friendship_status not null default 'pending'::public.friendship_status,
    "responded_at" timestamp with time zone
      );


alter table "public"."friendships" enable row level security;

alter table "public"."users" add column "referred_by" uuid;

alter table "public"."users" add column "username" text not null;

CREATE INDEX friendships_addressee_idx ON public.friendships USING btree (addressee, status);

CREATE UNIQUE INDEX friendships_pair_key ON public.friendships USING btree (LEAST(requester, addressee), GREATEST(requester, addressee));

CREATE UNIQUE INDEX friendships_pkey ON public.friendships USING btree (id);

CREATE INDEX friendships_requester_idx ON public.friendships USING btree (requester, status);

CREATE UNIQUE INDEX users_username_lower_key ON public.users USING btree (lower(username));

alter table "public"."friendships" add constraint "friendships_pkey" PRIMARY KEY using index "friendships_pkey";

alter table "public"."friendships" add constraint "friendships_addressee_fkey" FOREIGN KEY (addressee) REFERENCES public.users(id) ON DELETE CASCADE not valid;

alter table "public"."friendships" validate constraint "friendships_addressee_fkey";

alter table "public"."friendships" add constraint "friendships_no_self" CHECK ((requester <> addressee)) not valid;

alter table "public"."friendships" validate constraint "friendships_no_self";

alter table "public"."friendships" add constraint "friendships_requester_fkey" FOREIGN KEY (requester) REFERENCES public.users(id) ON DELETE CASCADE not valid;

alter table "public"."friendships" validate constraint "friendships_requester_fkey";

alter table "public"."users" add constraint "users_referred_by_fkey" FOREIGN KEY (referred_by) REFERENCES public.users(id) ON DELETE SET NULL not valid;

alter table "public"."users" validate constraint "users_referred_by_fkey";

alter table "public"."users" add constraint "users_username_check" CHECK ((username ~ '^[a-z0-9_.]{3,30}$'::text)) not valid;

alter table "public"."users" validate constraint "users_username_check";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.are_friends(a uuid, b uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1 from public.friendships f
    where f.status = 'accepted'
      and ((f.requester = a and f.addressee = b)
        or (f.requester = b and f.addressee = a))
  );
$function$
;

CREATE OR REPLACE FUNCTION public.generate_username(p_email text)
 RETURNS text
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  base text;
  candidate text;
  n int := 0;
begin
  base := regexp_replace(lower(split_part(p_email, '@', 1)), '[^a-z0-9_.]', '_', 'g');
  base := left(base, 26);
  if length(base) < 3 then base := base || '_user'; end if;

  candidate := base;
  while exists (select 1 from public.users where lower(username) = candidate) loop
    n := n + 1;
    candidate := base || n::text;
  end loop;
  return candidate;
end $function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  insert into public.users (id, email, username)
  values (new.id, new.email, public.generate_username(new.email));
  return new;
end $function$
;

grant delete on table "public"."friendships" to "anon";

grant insert on table "public"."friendships" to "anon";

grant references on table "public"."friendships" to "anon";

grant select on table "public"."friendships" to "anon";

grant trigger on table "public"."friendships" to "anon";

grant truncate on table "public"."friendships" to "anon";

grant update on table "public"."friendships" to "anon";

grant delete on table "public"."friendships" to "authenticated";

grant insert on table "public"."friendships" to "authenticated";

grant references on table "public"."friendships" to "authenticated";

grant select on table "public"."friendships" to "authenticated";

grant trigger on table "public"."friendships" to "authenticated";

grant truncate on table "public"."friendships" to "authenticated";

grant update on table "public"."friendships" to "authenticated";

grant delete on table "public"."friendships" to "service_role";

grant insert on table "public"."friendships" to "service_role";

grant references on table "public"."friendships" to "service_role";

grant select on table "public"."friendships" to "service_role";

grant trigger on table "public"."friendships" to "service_role";

grant truncate on table "public"."friendships" to "service_role";

grant update on table "public"."friendships" to "service_role";


  create policy "Friends can read course colors"
  on "public"."course_colors"
  as permissive
  for select
  to authenticated
using (public.are_friends(( SELECT auth.uid() AS uid), "user"));



  create policy "Friends can read events"
  on "public"."events"
  as permissive
  for select
  to authenticated
using (public.are_friends(( SELECT auth.uid() AS uid), "user"));



  create policy "Addressee can accept"
  on "public"."friendships"
  as permissive
  for update
  to authenticated
using (((( SELECT auth.uid() AS uid) = addressee) AND (status = 'pending'::public.friendship_status)))
with check (((( SELECT auth.uid() AS uid) = addressee) AND (status = 'accepted'::public.friendship_status)));



  create policy "Either party can remove"
  on "public"."friendships"
  as permissive
  for delete
  to authenticated
using (((( SELECT auth.uid() AS uid) = requester) OR (( SELECT auth.uid() AS uid) = addressee)));



  create policy "Users can read own friendships"
  on "public"."friendships"
  as permissive
  for select
  to authenticated
using (((( SELECT auth.uid() AS uid) = requester) OR (( SELECT auth.uid() AS uid) = addressee)));



  create policy "Users can send friend requests"
  on "public"."friendships"
  as permissive
  for insert
  to authenticated
with check (((( SELECT auth.uid() AS uid) = requester) AND (status = 'pending'::public.friendship_status)));



  create policy "Authenticated users can read profiles"
  on "public"."users"
  as permissive
  for select
  to authenticated
using (true);



